package com.github.max0961;

import javax.swing.*;
import java.awt.*;

public class GUI extends JFrame {

    private JTabbedPane tabbedPane;
    private JPanel rootPanel;
    private JTextField saveTextField;
    private JButton loadButton;
    private JTextField loadTextField;
    private JButton saveButton;
    private JComboBox fromLabelComboBox;
    private JComboBox toLabelcomboBox;
    private JTextField textField1;
    private JTextField textField3;
    private JTextField textField4;
    private JRadioButton densityRadioButton;
    private JRadioButton edgeNumberRadioButton;
    private JButton generateButton;
    private JButton button1;
    private JButton button2;
    private JComboBox comboBox1;
    private JButton removeButton;
    private JButton addButton;
    private JTextField textField2;
    private JPanel vertexEditingPanel;
    private JPanel edgesEditingPanel;
    private JTextField textField5;

    public GUI() {
        //this.setContentPane(rootPanel);
        add(rootPanel);
        setTitle("K shortest path routing");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        tabbedPane = new JTabbedPane();
        rootPanel.add(tabbedPane, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setName("");
        tabbedPane.addTab("Graph editing", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        panel2.setBorder(BorderFactory.createTitledBorder("Edit the graph"));
        edgesEditingPanel = new JPanel();
        edgesEditingPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(edgesEditingPanel, gbc);
        edgesEditingPanel.setBorder(BorderFactory.createTitledBorder("edge"));
        final JLabel label1 = new JLabel();
        label1.setText("from");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 0, 5, 5);
        edgesEditingPanel.add(label1, gbc);
        fromLabelComboBox = new JComboBox();
        fromLabelComboBox.setAlignmentX(0.0f);
        fromLabelComboBox.setMinimumSize(new Dimension(86, 24));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        edgesEditingPanel.add(fromLabelComboBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("to");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 0, 5);
        edgesEditingPanel.add(label2, gbc);
        toLabelcomboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        edgesEditingPanel.add(toLabelcomboBox, gbc);
        textField2 = new JTextField();
        textField2.setColumns(15);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        edgesEditingPanel.add(textField2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("weight");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 0, 5);
        edgesEditingPanel.add(label3, gbc);
        button2 = new JButton();
        button2.setLabel("Remove");
        button2.setText("Remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        edgesEditingPanel.add(button2, gbc);
        button1 = new JButton();
        button1.setLabel("Add");
        button1.setText("Add");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        edgesEditingPanel.add(button1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        vertexEditingPanel = new JPanel();
        vertexEditingPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(vertexEditingPanel, gbc);
        vertexEditingPanel.setBorder(BorderFactory.createTitledBorder("vertex"));
        comboBox1 = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vertexEditingPanel.add(comboBox1, gbc);
        textField1 = new JTextField();
        textField1.setColumns(15);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        vertexEditingPanel.add(textField1, gbc);
        addButton = new JButton();
        addButton.setText("Add");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vertexEditingPanel.add(addButton, gbc);
        removeButton = new JButton();
        removeButton.setText("Remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vertexEditingPanel.add(removeButton, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
        panel3.setBorder(BorderFactory.createTitledBorder("Random graph"));
        final JLabel label4 = new JLabel();
        label4.setText("vertex number");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        panel3.add(label4, gbc);
        textField3 = new JTextField();
        textField3.setColumns(8);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(textField3, gbc);
        textField4 = new JTextField();
        textField4.setColumns(8);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(textField4, gbc);
        densityRadioButton = new JRadioButton();
        densityRadioButton.setText("density");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(densityRadioButton, gbc);
        edgeNumberRadioButton = new JRadioButton();
        edgeNumberRadioButton.setText("edge number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(edgeNumberRadioButton, gbc);
        generateButton = new JButton();
        generateButton.setText("Generate");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(generateButton, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel4, gbc);
        panel4.setBorder(BorderFactory.createTitledBorder("Graph properties"));
        textField5 = new JTextField();
        textField5.setColumns(15);
        textField5.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(textField5, gbc);
        final JTextField textField6 = new JTextField();
        textField6.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(textField6, gbc);
        final JTextField textField7 = new JTextField();
        textField7.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(textField7, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Vertex number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Egde number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        panel4.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Density");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel4.add(label7, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer2, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel5, gbc);
        panel5.setBorder(BorderFactory.createTitledBorder("Save"));
        saveTextField = new JTextField();
        saveTextField.setColumns(40);
        panel5.add(saveTextField);
        saveButton = new JButton();
        saveButton.setText("Browse...");
        panel5.add(saveButton);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel6, gbc);
        panel6.setBorder(BorderFactory.createTitledBorder("Load"));
        loadTextField = new JTextField();
        loadTextField.setColumns(40);
        panel6.add(loadTextField);
        loadButton = new JButton();
        loadButton.setLabel("Browse...");
        loadButton.setText("Browse...");
        panel6.add(loadButton);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        tabbedPane.addTab("Algorithms", panel7);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new BorderLayout(0, 0));
        tabbedPane.addTab("Visualization", panel8);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        tabbedPane.addTab("Tests", panel9);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    class GraphTotal extends JComponent {
        final String[] xlabs = {"10", "100", "1000", "10000", "100000"};
        final double[] tottimes = {0.062417, 0.020193, 0.130112, 0.600274, 2.490668};

        public Dimension getPreferredSize() {
            return new Dimension(550, 500);
        }

        public void paintComponent(Graphics g) {

            Graphics2D g2 = (Graphics2D) g;
            g2.setFont(new Font("Arial", Font.ITALIC, 18));
            g2.drawString("ArrayList addChild() Total time", 150, 20);
            g2.drawLine(0, 450, 520, 450);
            g2.drawLine(50, 0, 50, 500);
            g2.setFont(new Font("Arial", Font.PLAIN, 14));

            for (int i = 0; i < 5; i++) {
                int ix = i * 100 + 100;
                g2.drawLine(ix, 440, ix, 460); // lines on horisontal line
                g2.drawString(xlabs[i], ix - 10, 470);
            }

            double scale = 400 / tottimes[4];

            for (int i = 0; i < 5; i++) {

                int ix0 = i * 100 + 100;
                int iy0 = 450 - (int) (tottimes[i] * scale);
                g2.drawRect(ix0 - 2, iy0 - 2, 4, 4);

                if (i < 4) {
                    int ix1 = (i + 1) * 100 + 100;
                    int iy1 = 450 - (int) (tottimes[i + 1] * scale);
                    g2.drawLine(ix0, iy0, ix1, iy1);
                }
            }
        }
    }

    class GraphMedian extends JComponent {
        final String[] xlabs = {"10", "100", "1000", "10000", "100000"};
        final double[] medtimes = {0.006242, 0.000202, 0.000130, 0.000060, 0.000025};

        public Dimension getPreferredSize() {
            return new Dimension(550, 500);
        }

        public void paintComponent(Graphics g) {

            Graphics2D g2 = (Graphics2D) g;
            g2.setFont(new Font("Arial", Font.ITALIC, 18));
            g2.drawString("ArrayList addChild() Median time", 150, 20);
            g2.drawLine(0, 450, 520, 450); //x
            g2.drawLine(50, 0, 50, 500); //y
            g2.setFont(new Font("Arial", Font.PLAIN, 14));

            for (int i = 0; i < 5; i++) { // vertical lines on horixontal line
                int ix = i * 100 + 100;
                g2.drawLine(ix, 440, ix, 460);
                g2.drawString(xlabs[i], ix - 10, 470);
            }

            double scale = 400 / medtimes[0];

            for (int i = 0; i < 5; i++) {

                int ix0 = i * 100 + 100;
                int iy0 = 450 - (int) (medtimes[i] * scale);
                g2.drawRect(ix0 - 2, iy0 - 2, 3, 3);

                if (i < 4) {
                    int ix1 = (i + 1) * 100 + 100;
                    int iy1 = 450 - (int) (medtimes[i + 1] * scale);
                    g2.drawLine(ix0, iy0, ix1, iy1);
                }
            }
        }

        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            $$$setupUI$$$();
        }

        /**
         * Method generated by IntelliJ IDEA GUI Designer
         * >>> IMPORTANT!! <<<
         * DO NOT edit this method OR call it in your code!
         *
         * @noinspection ALL
         */
        private void $$$setupUI$$$() {
            rootPanel = new JPanel();
            rootPanel.setLayout(new BorderLayout(0, 0));
            rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
            tabbedPane = new JTabbedPane();
            rootPanel.add(tabbedPane, BorderLayout.CENTER);
            final JPanel panel1 = new JPanel();
            panel1.setLayout(new GridBagLayout());
            panel1.setName("");
            tabbedPane.addTab("Graph editing", panel1);
            final JPanel panel2 = new JPanel();
            panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
            GridBagConstraints gbc;
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.fill = GridBagConstraints.BOTH;
            panel1.add(panel2, gbc);
            panel2.setBorder(BorderFactory.createTitledBorder("Save"));
            saveTextField = new JTextField();
            saveTextField.setColumns(40);
            panel2.add(saveTextField);
            saveButton = new JButton();
            saveButton.setText("Browse...");
            panel2.add(saveButton);
            final JPanel panel3 = new JPanel();
            panel3.setLayout(new GridBagLayout());
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 2;
            gbc.fill = GridBagConstraints.BOTH;
            panel1.add(panel3, gbc);
            panel3.setBorder(BorderFactory.createTitledBorder("Edit the graph"));
            vertexEditingPanel = new JPanel();
            vertexEditingPanel.setLayout(new GridBagLayout());
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.BOTH;
            panel3.add(vertexEditingPanel, gbc);
            vertexEditingPanel.setBorder(BorderFactory.createTitledBorder("vertex"));
            comboBox1 = new JComboBox();
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            vertexEditingPanel.add(comboBox1, gbc);
            textField1 = new JTextField();
            textField1.setColumns(15);
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.BOTH;
            vertexEditingPanel.add(textField1, gbc);
            addButton = new JButton();
            addButton.setText("Add");
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            vertexEditingPanel.add(addButton, gbc);
            removeButton = new JButton();
            removeButton.setText("Remove");
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 1;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            vertexEditingPanel.add(removeButton, gbc);
            edgesEditingPanel = new JPanel();
            edgesEditingPanel.setLayout(new GridBagLayout());
            gbc = new GridBagConstraints();
            gbc.gridx = 2;
            gbc.gridy = 0;
            gbc.gridheight = 2;
            gbc.fill = GridBagConstraints.BOTH;
            panel3.add(edgesEditingPanel, gbc);
            edgesEditingPanel.setBorder(BorderFactory.createTitledBorder("edge"));
            final JLabel label1 = new JLabel();
            label1.setText("from");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.EAST;
            gbc.insets = new Insets(5, 0, 5, 5);
            edgesEditingPanel.add(label1, gbc);
            fromLabelComboBox = new JComboBox();
            fromLabelComboBox.setAlignmentX(0.0f);
            fromLabelComboBox.setMinimumSize(new Dimension(86, 24));
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            edgesEditingPanel.add(fromLabelComboBox, gbc);
            final JLabel label2 = new JLabel();
            label2.setText("to");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.EAST;
            gbc.insets = new Insets(0, 0, 0, 5);
            edgesEditingPanel.add(label2, gbc);
            toLabelcomboBox = new JComboBox();
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            edgesEditingPanel.add(toLabelcomboBox, gbc);
            textField2 = new JTextField();
            textField2.setColumns(15);
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 2;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            edgesEditingPanel.add(textField2, gbc);
            final JLabel label3 = new JLabel();
            label3.setText("sidetracksWeight");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 2;
            gbc.anchor = GridBagConstraints.EAST;
            gbc.insets = new Insets(0, 0, 0, 5);
            edgesEditingPanel.add(label3, gbc);
            button2 = new JButton();
            button2.setLabel("Remove");
            button2.setText("Remove");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 4;
            gbc.gridwidth = 2;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            edgesEditingPanel.add(button2, gbc);
            button1 = new JButton();
            button1.setLabel("Add");
            button1.setText("Add");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 3;
            gbc.gridwidth = 2;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            edgesEditingPanel.add(button1, gbc);
            final JPanel spacer1 = new JPanel();
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.gridheight = 2;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            panel3.add(spacer1, gbc);
            final JPanel panel4 = new JPanel();
            panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.fill = GridBagConstraints.BOTH;
            panel1.add(panel4, gbc);
            panel4.setBorder(BorderFactory.createTitledBorder("Load"));
            loadTextField = new JTextField();
            loadTextField.setColumns(40);
            panel4.add(loadTextField);
            loadButton = new JButton();
            loadButton.setLabel("Browse...");
            loadButton.setText("Browse...");
            panel4.add(loadButton);
            final JPanel panel5 = new JPanel();
            panel5.setLayout(new GridBagLayout());
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 3;
            gbc.fill = GridBagConstraints.BOTH;
            panel1.add(panel5, gbc);
            panel5.setBorder(BorderFactory.createTitledBorder("Random graph"));
            final JLabel label4 = new JLabel();
            label4.setText("vertex number");
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.ipadx = 5;
            gbc.ipady = 5;
            panel5.add(label4, gbc);
            textField3 = new JTextField();
            textField3.setColumns(8);
            gbc = new GridBagConstraints();
            gbc.gridx = 2;
            gbc.gridy = 0;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            panel5.add(textField3, gbc);
            textField4 = new JTextField();
            textField4.setColumns(8);
            gbc = new GridBagConstraints();
            gbc.gridx = 2;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.WEST;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            panel5.add(textField4, gbc);
            densityRadioButton = new JRadioButton();
            densityRadioButton.setText("density");
            gbc = new GridBagConstraints();
            gbc.gridx = 1;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.WEST;
            panel5.add(densityRadioButton, gbc);
            edgeNumberRadioButton = new JRadioButton();
            edgeNumberRadioButton.setText("edge number");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 1;
            gbc.anchor = GridBagConstraints.WEST;
            panel5.add(edgeNumberRadioButton, gbc);
            generateButton = new JButton();
            generateButton.setText("Generate");
            gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 2;
            gbc.gridwidth = 3;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            panel5.add(generateButton, gbc);
            final JPanel panel6 = new JPanel();
            panel6.setLayout(new GridBagLayout());
            tabbedPane.addTab("Algorithms", panel6);
            final JPanel panel7 = new JPanel();
            panel7.setLayout(new GridBagLayout());
            tabbedPane.addTab("Visualization", panel7);
            final JPanel panel8 = new JPanel();
            panel8.setLayout(new GridBagLayout());
            tabbedPane.addTab("Tests", panel8);
        }

        /**
         * @noinspection ALL
         */
        public JComponent $$$getRootComponent$$$() {
            return rootPanel;
        }
    }
}
